# Generated by Django 3.2.9 on 2021-12-06 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CraftingTiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiers', models.CharField(choices=[('T1', 'tier_1'), ('T2', 'tier_2'), ('T3', 'tier_3'), ('T4', 'tier_4'), ('T5', 'tier_5')], default='T1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Factions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction', models.CharField(choices=[('COV', 'Covenant'), ('MAR', 'Marauder'), ('SYN', 'Syndicate'), ('UNF', 'No Faction')], default='UNF', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=255)),
                ('player_level', models.IntegerField(default=1)),
                ('player_company_id', models.ForeignKey(on_delete=models.SET(4), to='nwcs.company')),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('territory_name', models.CharField(choices=[('BW ', 'Brightwood'), ('CK', 'Cutlass Keys'), ('ER', 'Ebonscale Reach'), ('EF', 'Everfall'), ('FL', 'First Light'), ('MB', 'Monarchs Bluff'), ('MD', 'Mourningdale'), ('RW', 'Reekwater'), ('RS', 'Restless Shores'), ('WF', 'Weavers Fen'), ('WW', 'Windsward')], max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crafting',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nwcs.player')),
                ('arcana', models.IntegerField(default=0)),
                ('armoring', models.IntegerField(default=0)),
                ('cooking', models.IntegerField(default=0)),
                ('engineering', models.IntegerField(default=0)),
                ('furnishing', models.IntegerField(default=0)),
                ('jewel_crafting', models.IntegerField(default=0)),
                ('weapon_smithing', models.IntegerField(default=0)),
            ],
            bases=('nwcs.player',),
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nwcs.player')),
                ('exp_sword', models.IntegerField(default=500)),
                ('exp_shield', models.IntegerField(default=500)),
                ('exp_rapier', models.IntegerField(default=500)),
                ('exp_hatchet', models.IntegerField(default=500)),
                ('exp_great_axe', models.IntegerField(default=500)),
                ('exp_war_hammer', models.IntegerField(default=500)),
                ('exp_spear', models.IntegerField(default=500)),
                ('exp_bow', models.IntegerField(default=500)),
                ('exp_musket', models.IntegerField(default=500)),
                ('exp_life_staff', models.IntegerField(default=500)),
                ('exp_fire_staff', models.IntegerField(default=500)),
                ('exp_ice_gauntlet', models.IntegerField(default=500)),
                ('exp_void_gauntlet', models.IntegerField(default=500)),
                ('exp_head', models.IntegerField(default=500)),
                ('exp_chest', models.IntegerField(default=500)),
                ('exp_hands', models.IntegerField(default=500)),
                ('exp_legs', models.IntegerField(default=500)),
                ('exp_feet', models.IntegerField(default=500)),
                ('exp_amulet', models.IntegerField(default=500)),
                ('exp_ring', models.IntegerField(default=500)),
                ('exp_earring', models.IntegerField(default=500)),
            ],
            bases=('nwcs.player',),
        ),
        migrations.CreateModel(
            name='FortUpgrades',
            fields=[
                ('territory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nwcs.territory')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            bases=('nwcs.territory',),
        ),
        migrations.CreateModel(
            name='Gathering',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nwcs.player')),
                ('mining', models.IntegerField(default=0)),
                ('harvesting', models.IntegerField(default=0)),
                ('logging', models.IntegerField(default=0)),
                ('skinning', models.IntegerField(default=0)),
                ('fishing', models.IntegerField(default=0)),
            ],
            bases=('nwcs.player',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('territory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nwcs.territory')),
                ('housing_income', models.FloatField(default=0.0)),
                ('trading_income', models.FloatField(default=0.0)),
                ('refining_income', models.FloatField(default=0.0)),
                ('crafting_income', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            bases=('nwcs.territory',),
        ),
        migrations.CreateModel(
            name='Refining',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nwcs.player')),
                ('stone_cutting', models.IntegerField(default=0)),
                ('smelting', models.IntegerField(default=0)),
                ('weaving', models.IntegerField(default=0)),
                ('woodworking', models.IntegerField(default=0)),
                ('cooking', models.IntegerField(default=0)),
                ('tannning', models.IntegerField(default=0)),
            ],
            bases=('nwcs.player',),
        ),
        migrations.CreateModel(
            name='SettlementUpgrades',
            fields=[
                ('territory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nwcs.territory')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            bases=('nwcs.territory',),
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('territory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nwcs.territory')),
                ('housing_tax', models.FloatField(default=5.0)),
                ('trading_tax', models.FloatField(default=3.0)),
                ('refining_tax', models.FloatField(default=1.0)),
                ('crafting_tax', models.FloatField(default=1.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            bases=('nwcs.territory',),
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nwcs.player')),
                ('level_sword', models.IntegerField(default=1)),
                ('level_shield', models.IntegerField(default=1)),
                ('level_rapier', models.IntegerField(default=1)),
                ('level_hatchet', models.IntegerField(default=1)),
                ('level_great_axe', models.IntegerField(default=1)),
                ('level_war_hammer', models.IntegerField(default=1)),
                ('level_spear', models.IntegerField(default=1)),
                ('level_bow', models.IntegerField(default=1)),
                ('level_musket', models.IntegerField(default=1)),
                ('level_life_staff', models.IntegerField(default=1)),
                ('level_fire_staff', models.IntegerField(default=1)),
                ('level_ice_gauntlet', models.IntegerField(default=1)),
                ('level_void_gauntlet', models.IntegerField(default=1)),
            ],
            bases=('nwcs.player',),
        ),
    ]
