# Generated by Django 3.2.9 on 2021-12-06 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nwcs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crafting',
            name='player_ptr',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='player_ptr',
        ),
        migrations.RemoveField(
            model_name='gathering',
            name='player_ptr',
        ),
        migrations.RemoveField(
            model_name='refining',
            name='player_ptr',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='player_ptr',
        ),
        migrations.AddField(
            model_name='crafting',
            name='crafting_player_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nwcs.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expertise',
            name='exp_player_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nwcs.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gathering',
            name='gathering_player_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nwcs.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='refining',
            name='refining_player_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nwcs.player'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='weapon_player_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nwcs.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
