# Generated by Django 3.2.9 on 2021-12-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwcs', '0004_auto_20211206_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_primary_role',
            field=models.CharField(choices=[('Healer', 'Healer'), ('Tank', 'Tank'), ('Support', 'Support'), ('Ranged-DPS', 'Ranged-DPS'), ('Melee-DPS', 'Melee-DPS'), ('Hybrid', 'Hybrid')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_secondary_role',
            field=models.CharField(choices=[('Healer', 'Healer'), ('Tank', 'Tank'), ('Support', 'Support'), ('Ranged-DPS', 'Ranged-DPS'), ('Melee-DPS', 'Melee-DPS'), ('Hybrid', 'Hybrid')], default='', max_length=255),
        ),
    ]
