# Generated by Django 3.2.9 on 2021-12-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwcs', '0006_auto_20211207_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_pr_weapon_1',
            field=models.CharField(choices=[('Sword & Shield', 'Sword & Shield'), ('Rapier', 'Rapier'), ('Hatchet', 'Hatchet'), ('Great Axe', 'Great Axe'), ('War Hammer', 'War Hammer'), ('Spear', 'Spear'), ('Bow', 'Bow'), ('Musket', 'Musket'), ('Life Staff', 'Life Staff'), ('Fire Staff', 'Fire Staff'), ('Ice Gauntlet', 'Ice Gauntlet'), ('Void Gauntlet', 'Void Gauntlet')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_pr_weapon_2',
            field=models.CharField(choices=[('Sword & Shield', 'Sword & Shield'), ('Rapier', 'Rapier'), ('Hatchet', 'Hatchet'), ('Great Axe', 'Great Axe'), ('War Hammer', 'War Hammer'), ('Spear', 'Spear'), ('Bow', 'Bow'), ('Musket', 'Musket'), ('Life Staff', 'Life Staff'), ('Fire Staff', 'Fire Staff'), ('Ice Gauntlet', 'Ice Gauntlet'), ('Void Gauntlet', 'Void Gauntlet')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_sr_weapon_1',
            field=models.CharField(choices=[('Sword & Shield', 'Sword & Shield'), ('Rapier', 'Rapier'), ('Hatchet', 'Hatchet'), ('Great Axe', 'Great Axe'), ('War Hammer', 'War Hammer'), ('Spear', 'Spear'), ('Bow', 'Bow'), ('Musket', 'Musket'), ('Life Staff', 'Life Staff'), ('Fire Staff', 'Fire Staff'), ('Ice Gauntlet', 'Ice Gauntlet'), ('Void Gauntlet', 'Void Gauntlet')], default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_sr_weapon_2',
            field=models.CharField(choices=[('Sword & Shield', 'Sword & Shield'), ('Rapier', 'Rapier'), ('Hatchet', 'Hatchet'), ('Great Axe', 'Great Axe'), ('War Hammer', 'War Hammer'), ('Spear', 'Spear'), ('Bow', 'Bow'), ('Musket', 'Musket'), ('Life Staff', 'Life Staff'), ('Fire Staff', 'Fire Staff'), ('Ice Gauntlet', 'Ice Gauntlet'), ('Void Gauntlet', 'Void Gauntlet')], default='', max_length=255),
        ),
    ]
