# Generated by Django 3.2.9 on 2021-12-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nwcs', '0007_auto_20211207_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refining',
            name='cooking',
        ),
        migrations.RemoveField(
            model_name='refining',
            name='tannning',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='level_shield',
        ),
        migrations.AddField(
            model_name='refining',
            name='tanning',
            field=models.IntegerField(default=0),
        ),
    ]
